os: Visual Studio 2015

environment:
  matrix:
  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://static.rust-lang.org/rustup/archive/1.7.0/i686-pc-windows-gnu/rustup-init.exe -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - cmd: set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup update
  - rustc -vV
  - cargo -vV
  - cmd: set RUST_BACKTRACE=1
  - cmd: set RUSTFLAGS=-C target-feature=+crt-static

cache:
   - '%USERPROFILE%\.cargo'

build_script:
  - cargo build %cargoflags%

test_script:
  - cargo test %cargoflags%
  - cargo run --example timestamping %cargoflags%
  - cargo run --example configuration_change %cargoflags%
